# Generated by Django 4.1.4 on 2023-01-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Triagem', '0013_alter_triagem_frequencia_cardiaca_fc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico_atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidades', models.TextField(max_length=100)),
                ('hemorragia_digestiva_alta_HDA', models.TextField(max_length=500, null=True)),
                ('exame_fisico', models.TextField(max_length=500, null=True)),
                ('Diagnóstico', models.CharField(max_length=200)),
                ('classificação_internacional_doença_CID', models.CharField(max_length=50)),
                ('conduta', models.TextField(max_length=500)),
                ('alergia_sim', models.TextField(max_length=300, null=True)),
                ('medico_nome', models.TextField(max_length=40)),
                ('paciente_medico_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Triagem.triagem')),
            ],
        ),
    ]
