# Generated by Django 4.1.4 on 2023-03-03 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico_atendimento',
            options={'permissions': [('Acesso_permitido_Admin', 'Acesso permitido ao admin do sistema na UPA'), ('Acesso_permitido_medic', 'Acesso permitido aos médicos')]},
        ),
        #migrations.RemoveField(
         #   model_name='medico_atendimento',
          #  name='Diagnóstico',
        #),
        #migrations.RemoveField(
         #   model_name='medico_atendimento',
         #   name='alergia_sim',
        #),
        #migrations.RemoveField(
         #   model_name='medico_atendimento',
        #    name='classificação_internacional_doença_CID',
        #),
        #migrations.RemoveField(
         #   model_name='medico_atendimento',
          #  name='comorbidades',
        #),
        #migrations.RemoveField(
        #    model_name='medico_atendimento',
        #    name='hemorragia_digestiva_alta_HDA',
        #),
       # migrations.AddField(
        #    model_name='medico_atendimento',
         #   name='Diagnostico',
          #  field=models.CharField(default='Não se aplica', max_length=200, null=True),
        #),
        #migrations.AddField(
        #    model_name='medico_atendimento',
        #    name='classificacao_internacional_doenca_CID',
        #    field=models.CharField(default='Não se aplica', max_length=50, null=True),
        #),
        migrations.AddField(
            model_name='medico_atendimento',
            name='data_medico',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='historico_doenca_atual_HDA',
            field=models.TextField(default='Não se aplica', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='hora_medico',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='tempo_espera_paciente',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico_atendimento',
            name='conduta',
            field=models.TextField(default='Não se aplica', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medico_atendimento',
            name='exame_fisico',
            field=models.TextField(default='Não se aplica', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medico_atendimento',
            name='medico_nome',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_users', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
