# Generated by Django 4.1.4 on 2023-03-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0002_alter_medico_atendimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico_atendimento',
            name='Diagnóstico',
        ),
        migrations.RemoveField(
            model_name='medico_atendimento',
            name='comorbidades',
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='Diagnostico',
            field=models.CharField(default='Não se aplica', max_length=200, null=True),
        ),
    ]
