# Generated by Django 4.1.4 on 2023-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0003_remove_medico_atendimento_diagnóstico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico_atendimento',
            name='alergia_sim',
        ),
        migrations.RemoveField(
            model_name='medico_atendimento',
            name='classificação_internacional_doença_CID',
        ),
        migrations.RemoveField(
            model_name='medico_atendimento',
            name='hemorragia_digestiva_alta_HDA',
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='classificacao_internacional_doenca_CID',
            field=models.CharField(default='Não se aplica', max_length=50, null=True),
        ),
    ]
