# Generated by Django 4.1.4 on 2023-03-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
