# Generated by Django 4.1.4 on 2023-03-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crm',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
