# Generated by Django 4.1.4 on 2023-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0008_alter_customuser_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='crm',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
