# Generated by Django 4.1.4 on 2023-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0009_alter_customuser_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='crm',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
