# Generated by Django 4.1.4 on 2023-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0010_alter_customuser_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamar_P_para_atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('data_chamada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
