# Generated by Django 4.1.4 on 2023-03-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0011_chamar_p_para_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='data_chamada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='nome_paciente',
            field=models.CharField(max_length=100),
        ),
    ]
