# Generated by Django 4.1.4 on 2023-03-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0012_alter_chamar_p_para_atendimento_data_chamada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='data_chamada',
            field=models.DateField(null=True),
        ),
    ]
