# Generated by Django 4.1.4 on 2023-03-07 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0013_alter_chamar_p_para_atendimento_data_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamar_p_para_atendimento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
