# Generated by Django 4.1.4 on 2023-03-09 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0014_chamar_p_para_atendimento_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamar_p_para_atendimento',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
