# Generated by Django 4.1.4 on 2023-03-16 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0015_chamar_p_para_atendimento_data_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSala', models.CharField(max_length=40)),
                ('profissionalSaude', models.ForeignKey(limit_choices_to={'groups__name__in': ['groups_Medico', 'groups_Enfermagem']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
