# Generated by Django 4.1.4 on 2023-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0017_cadastrosala_alter_salas_atendimento_nomesala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosala',
            name='descricao_Sala',
            field=models.CharField(max_length=200, verbose_name='Descreva a ulitilização da sala. Ex.: Sala de atendimento pediátrico'),
        ),
        migrations.AlterField(
            model_name='cadastrosala',
            name='nome_Sala',
            field=models.CharField(max_length=40, verbose_name='Escreva o nome da sala. Ex: Sala 01'),
        ),
    ]
