# Generated by Django 4.1.4 on 2023-03-17 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0018_alter_cadastrosala_descricao_sala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosala',
            name='descricao_Sala',
            field=models.TextField(max_length=200, verbose_name='Descreva a ulitilização da sala. Ex.: Sala de atendimento pediátrico'),
        ),
        migrations.AlterField(
            model_name='salas_atendimento',
            name='profissionalSaude',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['group_Medicos', 'group_Enfermagem']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
