# Generated by Django 4.1.4 on 2023-03-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0019_alter_cadastrosala_descricao_sala_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
    ]
