# Generated by Django 4.1.4 on 2023-03-18 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0020_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamar_p_para_atendimento',
            name='profissionalSaude',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
