# Generated by Django 4.1.4 on 2023-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0021_chamar_p_para_atendimento_profissionalsaude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='data_chamada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
