# Generated by Django 4.1.4 on 2023-03-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicos', '0023_chamar_p_para_atendimento_profissionalsaude_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='profissionalSaude_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
