# Generated by Django 4.1.4 on 2023-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0024_alter_chamar_p_para_atendimento_profissionalsaude_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamar_p_para_atendimento',
            name='profissionalSaude',
        ),
    ]
