# Generated by Django 4.1.4 on 2023-03-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0058_remove_triagem_alergias_and_more'),
        ('Medicos', '0026_alter_medico_atendimento_paciente_medico_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='paciente_medico_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Triagem.triagem'),
        ),
    ]
