# Generated by Django 4.1.4 on 2023-04-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0027_alter_medico_atendimento_paciente_medico_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='cid_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=4, null=True)),
                ('codigo', models.CharField(max_length=12, null=True)),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('codigo_Cid10', models.CharField(max_length=50)),
            ],
        ),
    ]
