# Generated by Django 4.1.4 on 2023-04-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0028_cid_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid_10',
            name='capitulo',
        ),
    ]
