# Generated by Django 4.1.4 on 2023-04-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0029_remove_cid_10_capitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='classificacao_internacional_doenca_CID',
            field=models.ForeignKey(default='Não se aplica', null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicos.cid_10'),
        ),
    ]
