# Generated by Django 4.2 on 2023-07-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0030_alter_medico_atendimento_classificacao_internacional_doenca_cid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cid_10',
            options={'ordering': ['id']},
        ),
    ]
