# Generated by Django 4.2 on 2023-07-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0090_alter_atendimento_especializado_situacao'),
        ('Medicos', '0031_alter_cid_10_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='paciente_medico_atendimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Triagem.triagem'),
        ),
    ]
