# Generated by Django 4.2.7 on 2023-11-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0033_alter_cadastrosala_descricao_sala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='nome_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicos.medico_atendimento'),
        ),
    ]
