# Generated by Django 4.2.7 on 2023-12-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0165_alter_atendimento_especializado_situacao'),
        ('Medicos', '0035_alter_medico_atendimento_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='paciente_medico_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Triagem.triagem'),
        ),
    ]
