# Generated by Django 4.2.7 on 2023-12-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0039_alter_chamar_p_para_atendimento_nome_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamar_p_para_atendimento',
            options={'ordering': ['-id']},
        ),
    ]
