# Generated by Django 4.2.7 on 2023-12-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0188_alter_atendimento_especializado_situacao'),
        ('Medicos', '0040_alter_chamar_p_para_atendimento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamar_p_para_atendimento',
            name='nome_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Triagem.triagem'),
        ),
    ]
