# Generated by Django 4.2.7 on 2023-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0041_alter_chamar_p_para_atendimento_nome_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamar_p_para_atendimento',
            name='chamado',
            field=models.BooleanField(default=False),
        ),
    ]
