# Generated by Django 4.2.7 on 2023-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0042_chamar_p_para_atendimento_chamado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=255)),
                ('principio_ativo', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, null=True)),
                ('concentracao', models.CharField(blank=True, max_length=50, null=True)),
                ('via_administracao', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='medicamento',
            field=models.ManyToManyField(to='Medicos.medicamento'),
        ),
    ]
