# Generated by Django 4.2.7 on 2023-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0224_alter_atendimento_especializado_situacao'),
        ('Medicos', '0043_medicamento_medico_atendimento_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salva_modelo_exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Ex: Nome do modelo', max_length=40)),
                ('conteudo', models.TextField(default='Ex: Solicito os seguintes exames ...', max_length=500)),
                ('exame', models.ManyToManyField(to='Triagem.exames_model')),
            ],
        ),
    ]
