# Generated by Django 4.2.7 on 2024-02-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0044_salva_modelo_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas_atendimento',
            name='nomeSala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicos.cadastrosala'),
        ),
    ]
