# Generated by Django 4.2.7 on 2024-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0045_alter_salas_atendimento_nomesala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='medicamento',
            field=models.ManyToManyField(blank=True, to='Medicos.medicamento'),
        ),
    ]
