# Generated by Django 4.2.7 on 2024-03-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0046_alter_medico_atendimento_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico_atendimento',
            name='chamadas_contabilizadas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medico_atendimento',
            name='respondeu_ao_chamado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
