# Generated by Django 4.2.7 on 2024-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0048_alter_chamar_p_para_atendimento_data_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico_atendimento',
            name='relatorio_impresso',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
