# Generated by Django 4.2.7 on 2024-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0049_medico_atendimento_relatorio_impresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico_atendimento',
            name='relatorio_impresso',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
