# Generated by Django 4.2 on 2023-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config_Marquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_medico', models.BooleanField(default=True, null=True)),
                ('gif_enfermera', models.BooleanField(default=True, null=True)),
                ('gif_Ze_gotina', models.BooleanField(default=True, null=True)),
                ('mensagem', models.TextField(default=False, null=True)),
            ],
        ),
    ]
