# Generated by Django 4.2 on 2023-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_marquee',
            name='gif_Ze_gotina',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='config_marquee',
            name='gif_enfermera',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='config_marquee',
            name='gif_medico',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='config_marquee',
            name='mensagem',
            field=models.TextField(default=True, null=True),
        ),
    ]
