# Generated by Django 4.2 on 2023-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0002_alter_config_marquee_gif_ze_gotina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_marquee',
            name='mensagem',
            field=models.TextField(default='', null=True),
        ),
    ]
