# Generated by Django 4.2 on 2023-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0003_alter_config_marquee_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='distancia',
            field=models.IntegerField(default='40'),
        ),
    ]
