# Generated by Django 4.2 on 2023-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0004_config_marquee_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='bem_vindo_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='config_marquee',
            name='bem_vindo_msg',
            field=models.TextField(default='Bem vindos à UPA de Vera Cruz '),
        ),
    ]
