# Generated by Django 4.2 on 2023-04-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0005_config_marquee_bem_vindo_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='bem_vindo_ativa_coracao',
            field=models.BooleanField(default=True),
        ),
    ]
