# Generated by Django 4.2 on 2023-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0006_config_marquee_bem_vindo_ativa_coracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='data_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='config_marquee',
            name='hora_ativa',
            field=models.BooleanField(default=True),
        ),
    ]
