# Generated by Django 4.2 on 2023-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0007_config_marquee_data_ativa_config_marquee_hora_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='letreiro_ativa',
            field=models.BooleanField(default=True),
        ),
    ]
