# Generated by Django 4.2 on 2023-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0008_config_marquee_letreiro_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_marquee',
            name='mensagem_ativa',
            field=models.BooleanField(default=True),
        ),
    ]
