# Generated by Django 4.2 on 2023-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0009_config_marquee_mensagem_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_marquee',
            name='distancia',
            field=models.IntegerField(default='60'),
        ),
    ]
