# Generated by Django 4.2 on 2023-04-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0010_alter_config_marquee_distancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Backgroud_Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
