# Generated by Django 4.2 on 2023-04-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0012_video_backgroud_painel_datahora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video_backgroud_painel',
            options={'ordering': ['-dataHora']},
        ),
    ]
