# Generated by Django 4.2 on 2023-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0013_alter_video_backgroud_painel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_backgroud_painel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video_backgroud_painel',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
