# Generated by Django 4.2.7 on 2024-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0015_alter_config_marquee_gif_ze_gotina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificate_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name_atualiza', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
