# Generated by Django 4.2.7 on 2024-04-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0016_notificate_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate_system',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
