# Generated by Django 4.2.7 on 2024-04-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0017_notificate_system_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificate_system',
            name='name_atualiza',
        ),
    ]
