# Generated by Django 4.2.7 on 2024-04-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configUPA', '0018_remove_notificate_system_name_atualiza'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate_system',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_notificacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
