# Generated by Django 4.2.7 on 2024-04-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0019_notificate_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate_system',
            name='name',
            field=models.TextField(default='Atualização de fim de ano', max_length=100),
        ),
    ]
