# Generated by Django 4.2.7 on 2024-04-12 23:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0020_notificate_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificate_system',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Descrever a atualização'),
        ),
    ]
