# Generated by Django 4.2.7 on 2024-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUPA', '0021_alter_notificate_system_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificate_system',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='notificate_system',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
