from .pagina_inicial.pagina_inicial import *
from .cadastra_paciente import *
from .cadastra_sexo import *
from .cadastra_pais import *
from .cadastra_estado import *
from .cadastra_cidade import *
from .cadastra_bairro import *
from .cadastra_etnia import *
from .cadastra_Rua import *
from .pefil_usuario_simples import *
from .envio_triagem import *
from .painel import *
from .outras_listagens import *
