# Generated by Django 4.1.4 on 2022-12-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atendimento', '0003_genero_sexual_ficha_de_atendimento_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial_PA', models.CharField(default='120/80 mmHg', max_length=11)),
                ('frequencia_cardiaca_FC', models.CharField(default='35 bpm', max_length=7)),
                ('frequencia_respiratoria_FR', models.CharField(default='20 ipm', max_length=6)),
                ('saturacao_de_oxigenio_SPO2', models.CharField(default='94%', max_length=3)),
                ('hemoglicoteste_HGT', models.CharField(default='75 mg/dL', max_length=9)),
                ('temperatura_TEMP', models.CharField(default='36,5 °C', max_length=7)),
                ('peso', models.CharField(default='62 kg', max_length=6)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atendimento.ficha_de_atendimento')),
            ],
        ),
    ]
