# Generated by Django 4.1.4 on 2022-12-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0008_alter_envio_triagem_data_envio_triagem'),
        ('Triagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifica_risco_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='triagem',
            name='hora_triagem',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='data_triagem',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca_FC',
            field=models.CharField(default='35 bpm', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_respiratoria_FR',
            field=models.CharField(default='20 ipm', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='hemoglicoteste_HGT',
            field=models.CharField(default='75 mg/dL', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atendimento.envio_triagem'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.CharField(default='62 kg', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.CharField(default='120/80 mmHg', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='saturacao_de_oxigenio_SPO2',
            field=models.CharField(default='94%', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura_TEMP',
            field=models.CharField(default='36,5 °C', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='classifica_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Triagem.classifica_risco_model', verbose_name='Classificação de Emergência'),
        ),
    ]
