# Generated by Django 4.1.4 on 2022-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0002_classifica_risco_model_triagem_hora_triagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifica_risco_model',
            name='classifica_tipo',
            field=models.CharField(default='Vermelho', max_length=30),
        ),
        migrations.AddField(
            model_name='classifica_risco_model',
            name='descri',
            field=models.CharField(default='', max_length=200),
        ),
    ]
