# Generated by Django 4.1.4 on 2022-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0003_classifica_risco_model_classifica_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifica_risco_model',
            name='descri',
            field=models.CharField(default='', max_length=500),
        ),
    ]
