# Generated by Django 4.1.4 on 2022-12-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0005_alter_classifica_risco_model_descri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifica_risco_model',
            options={'ordering': ['classifica_tipo']},
        ),
    ]
