# Generated by Django 4.1.4 on 2022-12-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0006_alter_classifica_risco_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifica_risco_model',
            options={'ordering': ['-classifica_tipo']},
        ),
    ]
