# Generated by Django 4.1.4 on 2023-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0010_triagem_ficha_de_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='paciente',
            new_name='paciente_triagem',
        ),
    ]
