# Generated by Django 4.1.4 on 2023-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0012_remove_triagem_ficha_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca_FC',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_respiratoria_FR',
            field=models.CharField(default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='hemoglicoteste_HGT',
            field=models.CharField(default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.CharField(default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.CharField(default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='saturacao_de_oxigenio_SPO2',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura_TEMP',
            field=models.CharField(default='', max_length=7, null=True),
        ),
    ]
