# Generated by Django 4.1.4 on 2023-01-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0013_alter_triagem_frequencia_cardiaca_fc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagem',
            options={'ordering': ['classifica_tipo', 'data_triagem']},
        ),
    ]
