# Generated by Django 4.1.4 on 2023-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0014_alter_triagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='observacao',
            field=models.TextField(default='', max_length=500, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
