# Generated by Django 4.1.4 on 2023-01-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0015_triagem_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='observacao',
            field=models.TextField(max_length=700, verbose_name='Observação'),
        ),
    ]
