# Generated by Django 4.1.4 on 2023-01-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0019_alter_envio_triagem_paciente_envio_triagem'),
        ('Triagem', '0016_alter_triagem_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='paciente_triagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_envio_triagem', to='Atendimento.envio_triagem'),
        ),
    ]
