# Generated by Django 4.1.4 on 2023-01-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0018_triagem_final_triagem_triagem_final_triagem_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagem',
            options={},
        ),
        migrations.AlterField(
            model_name='triagem',
            name='final_triagem',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
