# Generated by Django 4.1.4 on 2023-01-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0019_alter_triagem_options_alter_triagem_final_triagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagem',
            options={'ordering': ['classifica_tipo', 'hora_triagem', 'paciente_triagem__paciente_envio_triagem__idade']},
        ),
    ]
