# Generated by Django 4.1.4 on 2023-01-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0020_alter_triagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='preescrever_medicamento_medico',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
