# Generated by Django 4.1.4 on 2023-01-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0021_triagem_preescrever_medicamento_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='preescrever_medicamento_medico',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
