# Generated by Django 4.1.4 on 2023-01-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0022_alter_triagem_preescrever_medicamento_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='enviar_ambulatorio',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], max_length=3, null='False'),
            preserve_default='False',
        ),
    ]
