# Generated by Django 4.1.4 on 2023-01-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0023_triagem_enviar_ambulatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='final_medico_atendimento',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='preescrever_medicamento_medico',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
