# Generated by Django 4.1.4 on 2023-01-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0024_triagem_final_medico_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='final_triagem',
            field=models.CharField(default='', max_length=3),
        ),
    ]
