# Generated by Django 4.1.4 on 2023-01-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0025_alter_triagem_final_triagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='final_triagem',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
