# Generated by Django 4.1.4 on 2023-01-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0027_alter_triagem_frequencia_cardiaca_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='enviar_ambulatorio',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], max_length=3, null=True),
        ),
    ]
