# Generated by Django 4.1.4 on 2023-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0030_alter_triagem_pressao_arterial_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.CharField(default='', help_text='Por favor, digite o valor no seguinte formato: <em>120x80 mmHg</em>.', max_length=11),
        ),
    ]
