# Generated by Django 4.1.4 on 2023-01-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0031_alter_triagem_pressao_arterial_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.CharField(default='', max_length=11),
        ),
    ]
