# Generated by Django 4.1.4 on 2023-02-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0032_alter_triagem_pressao_arterial_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='atestado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='encaminhamento',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='exames',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
