# Generated by Django 4.1.4 on 2023-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0034_alter_triagem_atestado_alter_triagem_encaminhamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='alergias',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triagem',
            name='alergias_content',
            field=models.TextField(max_length=700, null=True, verbose_name='Observação'),
        ),
    ]
