# Generated by Django 4.1.4 on 2023-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0035_triagem_alergias_triagem_alergias_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias_content',
            field=models.TextField(max_length=700, null=True, verbose_name='Descreva a alergias do paciente'),
        ),
    ]
