# Generated by Django 4.1.4 on 2023-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0037_alter_triagem_alergias_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='nome_da_enfermeira',
            field=models.CharField(default='', max_length=20),
        ),
    ]
