# Generated by Django 4.1.4 on 2023-03-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0038_triagem_nome_da_enfermeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('registrado_triagem', models.BooleanField(default=False)),
            ],
        ),
    ]
