# Generated by Django 4.1.4 on 2023-03-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0039_paciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Chamar_Paciente',
        ),
    ]
