# Generated by Django 4.1.4 on 2023-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0041_delete_chamar_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamarPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField()),
                ('nome_paciente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_envio_triagem', models.CharField(max_length=255)),
            ],
        ),
    ]
