# Generated by Django 4.1.4 on 2023-03-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0042_chamarpaciente_enviotriagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamarpaciente',
            name='id_paciente',
            field=models.CharField(max_length=255),
        ),
    ]
