# Generated by Django 4.1.4 on 2023-03-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0043_alter_chamarpaciente_id_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamarpaciente',
            old_name='id_paciente',
            new_name='paciente_id',
        ),
    ]
