# Generated by Django 4.1.4 on 2023-03-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0044_rename_id_paciente_chamarpaciente_paciente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamarpaciente',
            old_name='paciente_id',
            new_name='id_paciente',
        ),
    ]
