# Generated by Django 4.1.4 on 2023-03-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0045_rename_paciente_id_chamarpaciente_id_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvioTriagem',
        ),
        migrations.RenameField(
            model_name='chamarpaciente',
            old_name='id_paciente',
            new_name='paciente_id',
        ),
    ]
