# Generated by Django 4.1.4 on 2023-03-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0046_delete_enviotriagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamarpaciente',
            old_name='paciente_id',
            new_name='id_paciente',
        ),
    ]
