# Generated by Django 4.1.4 on 2023-03-13 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0047_rename_paciente_id_chamarpaciente_id_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamarpaciente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
