# Generated by Django 4.1.4 on 2023-03-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0049_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
