# Generated by Django 4.1.4 on 2023-03-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0053_customuser_nome_customuser_sobrenome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserTriagem',
        ),
    ]
