# Generated by Django 4.1.4 on 2023-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0054_rename_customuser_customusertriagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertriagem',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
