# Generated by Django 4.1.4 on 2023-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0056_customusertriagem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], max_length=3, null=True),
        ),
    ]
