# Generated by Django 4.1.4 on 2023-03-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0057_alter_triagem_alergias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='alergias_content',
        ),
    ]
