# Generated by Django 4.1.4 on 2023-03-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0058_remove_triagem_alergias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='atestado',
        ),
    ]
