# Generated by Django 4.1.4 on 2023-03-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0059_remove_triagem_atestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='atestado',
            field=models.TextField(default='Digite a quantidade de dias que o paciente irá ficar de repouso', max_length=10, null=True),
        ),
    ]
