# Generated by Django 4.1.4 on 2023-04-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0060_triagem_atestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='atestado',
            field=models.TextField(default='Digite a quantidade de dias que o paciente irá ficar de repouso', max_length=15, null=True),
        ),
    ]
