# Generated by Django 4.2 on 2023-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0063_alter_exames_model_d_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exames_model',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='exames_model',
            name='d_v',
        ),
        migrations.RemoveField(
            model_name='exames_model',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='exames_model',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='exames_model',
            name='valor',
        ),
        migrations.AddField(
            model_name='exames_model',
            name='nome_exame',
            field=models.CharField(default='Nenhuma solicitação de exames', max_length=50),
            preserve_default=False,
        ),
    ]
