# Generated by Django 4.2 on 2023-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0064_remove_exames_model_classificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='exames',
        ),
        migrations.AddField(
            model_name='triagem',
            name='exames',
            field=models.ManyToManyField(related_name='related_exames', to='Triagem.exames_model'),
        ),
    ]
