# Generated by Django 4.2 on 2023-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0065_remove_triagem_exames_triagem_exames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='exames',
            field=models.ManyToManyField(max_length=300, related_name='related_exames', to='Triagem.exames_model'),
        ),
    ]
