# Generated by Django 4.2 on 2023-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0066_alter_triagem_exames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='exames',
            field=models.ManyToManyField(null=True, related_name='related_exames', to='Triagem.exames_model'),
        ),
    ]
