# Generated by Django 4.2 on 2023-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0067_alter_triagem_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='exames',
        ),
        migrations.AddField(
            model_name='triagem',
            name='exames',
            field=models.CharField(default='', max_length=70),
        ),
    ]
