# Generated by Django 4.2 on 2023-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0068_remove_triagem_exames_triagem_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='exames',
        ),
        migrations.AddField(
            model_name='triagem',
            name='exames',
            field=models.ManyToManyField(to='Triagem.exames_model'),
        ),
    ]
