# Generated by Django 4.2 on 2023-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0070_triagem_alergias_triagem_conteudo_alergia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.BooleanField(choices=[('1', 'Sim'), ('0', 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='conteudo_alergia',
            field=models.TextField(default='Não possui alergias', max_length=300, null=True),
        ),
    ]
