# Generated by Django 4.2 on 2023-04-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0071_alter_triagem_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.BooleanField(choices=[('1', 'Sim'), ('0', 'Não')], default=2),
        ),
    ]
