# Generated by Django 4.2 on 2023-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0072_alter_triagem_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.BooleanField(choices=[('0', 'Não'), ('1', 'Sim')], default=2),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='enviar_ambulatorio',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], max_length=3),
        ),
    ]
