# Generated by Django 4.2 on 2023-04-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0074_alter_triagem_conteudo_alergia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='conteudo_alergia',
            field=models.TextField(default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)', max_length=300, null=True),
        ),
    ]
