# Generated by Django 4.2 on 2023-04-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0075_alter_triagem_conteudo_alergia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
    ]
