# Generated by Django 4.2 on 2023-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0076_alter_triagem_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='alergias',
            field=models.CharField(choices=[('', ''), ('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='enviar_ambulatorio',
            field=models.CharField(choices=[('', ''), ('0', 'Não'), ('1', 'Sim')], max_length=3),
        ),
    ]
