# Generated by Django 4.2 on 2023-05-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0077_alter_triagem_alergias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='conteudo_alergia',
        ),
    ]
