# Generated by Django 4.2 on 2023-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0079_alter_triagem_atestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='exames',
            field=models.ManyToManyField(null=True, to='Triagem.exames_model'),
        ),
    ]
