# Generated by Django 4.2 on 2023-05-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0081_alter_triagem_nome_da_enfermeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames_model',
            name='nome_exame',
            field=models.CharField(default='Nenhuma solicitação de exame', max_length=50),
        ),
    ]
