# Generated by Django 4.2 on 2023-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0082_alter_exames_model_nome_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca_FC',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_respiratoria_FR',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='hemoglicoteste_HGT',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='saturacao_de_oxigenio_SPO2',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura_TEMP',
            field=models.IntegerField(default=''),
        ),
    ]
