# Generated by Django 4.2 on 2023-06-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0084_alter_triagem_frequencia_cardiaca_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
