# Generated by Django 4.2 on 2023-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0086_alter_triagem_altura_alter_triagem_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca_FC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_respiratoria_FR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='saturacao_de_oxigenio_SPO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura_TEMP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
