# Generated by Django 4.2 on 2023-07-09 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0087_alter_triagem_frequencia_cardiaca_fc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento_especializado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('2', 'Liberado'), ('1', 'Em atendimento'), ('0', 'Aguardando')], max_length=30)),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Triagem.tipos_atendimento')),
            ],
        ),
    ]
