# Generated by Django 4.2 on 2023-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0091_triagem_atend_especializado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento_especializado',
            name='descreve_solicitacao',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('1', 'Em atendimento'), ('0', 'Aguardando'), ('2', 'Liberado')], max_length=30),
        ),
    ]
