# Generated by Django 4.2 on 2023-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0092_atendimento_especializado_descreve_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('0', 'Aguardando'), ('2', 'Liberado'), ('1', 'Em atendimento')], max_length=30, null=True),
        ),
    ]
