# Generated by Django 4.2 on 2023-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0093_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('1', 'Em atendimento'), ('2', 'Liberado'), ('0', 'Aguardando')], max_length=30, null=True),
        ),
    ]
