# Generated by Django 4.2 on 2023-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0094_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento_especializado',
            name='pk_paciente',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
