# Generated by Django 4.2 on 2023-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0097_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento_especializado',
            name='nome_medico',
            field=models.CharField(default='Dr. Teste', max_length=30),
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('1', 'Em atendimento'), ('2', 'Liberado'), ('0', 'Aguardando')], default='Aguardando', max_length=30, null=True),
        ),
    ]
