# Generated by Django 4.2 on 2023-07-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0098_atendimento_especializado_nome_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
    ]
