# Generated by Django 4.2 on 2023-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0107_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Liberado', 'Liberado')], default='Aguardando', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='final_triagem_time',
            field=models.DateField(auto_now=True),
        ),
    ]
