# Generated by Django 4.2 on 2023-07-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0110_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='enviar_ambulatorio',
        ),
    ]
