# Generated by Django 4.2 on 2023-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0118_alter_atendimento_especializado_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA',
            field=models.FloatField(blank=True, null=True, verbose_name='Pressão arterial (mínima) PA-1'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao_arterial_PA_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Pressão arterial (máxima)) PA-2'),
        ),
    ]
