# Generated by Django 4.2.7 on 2023-11-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0128_alter_atendimento_especializado_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
    ]
