# Generated by Django 4.2 on 2023-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0132_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Liberado', 'Liberado'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
    ]
