# Generated by Django 4.2.7 on 2023-11-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0142_alter_classifica_risco_model_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifica_risco_model',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Em atendimento', 'Em atendimento'), ('Liberado', 'Liberado'), ('Aguardando', 'Aguardando')], default='Aguardando', max_length=30, null=True),
        ),
    ]
