# Generated by Django 4.2.7 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0160_alter_atendimento_especializado_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_cardiaca_FC',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='frequencia_respiratoria_FR',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='hemoglicoteste_HGT',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='saturacao_de_oxigenio_SPO2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='temperatura_TEMP',
            field=models.FloatField(blank=True),
        ),
    ]
