# Generated by Django 4.2.7 on 2023-11-29 15:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0163_alter_atendimento_especializado_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
