# Generated by Django 4.2.7 on 2023-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0168_triagem_nome_acompanhante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='nome_acompanhante',
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Em atendimento', 'Em atendimento'), ('Aguardando', 'Aguardando')], default='Aguardando', max_length=30, null=True),
        ),
    ]
