# Generated by Django 4.2.7 on 2023-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0199_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='data_envio_a_classificao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='hora_envio_a_classificao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
    ]
