# Generated by Django 4.2.7 on 2023-12-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0200_triagem_data_envio_a_classificao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Em atendimento', 'Em atendimento'), ('Aguardando', 'Aguardando'), ('Liberado', 'Liberado')], default='Aguardando', max_length=30, null=True),
        ),
    ]
