# Generated by Django 5.0 on 2023-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0220_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Liberado', 'Liberado')], default='Aguardando', max_length=30, null=True),
        ),
    ]
