<<<<<<< HEAD
# Generated by Django 4.2.7 on 2024-03-08 17:28
=======
# Generated by Django 4.2.7 on 2024-03-11 11:36
>>>>>>> 3a0734e0a0de8c30c1d302824980d29878a2c1fa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0370_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
<<<<<<< HEAD
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
=======
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Liberado', 'Liberado'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
>>>>>>> 3a0734e0a0de8c30c1d302824980d29878a2c1fa
        ),
    ]
