# Generated by Django 4.2.7 on 2024-03-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0373_triagem_chamadas_contabilizadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='respondeu_ao_chamado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Em atendimento', 'Em atendimento'), ('Aguardando', 'Aguardando'), ('Liberado', 'Liberado')], default='Aguardando', max_length=30, null=True),
        ),
    ]
