# Generated by Django 4.2.7 on 2024-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0415_alter_atendimento_especializado_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Em atendimento', 'Em atendimento'), ('Aguardando', 'Aguardando')], default='Aguardando', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='medico_respondeu_ao_chamado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='respondeu_ao_chamado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
