# Generated by Django 4.2.7 on 2024-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0422_rename_medico_respondeu_chamado_triagem_medico_respondeu_ao_chamado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='respondeu_ao_chamado_medico',
        ),
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento')], default='Aguardando', max_length=30, null=True),
        ),
    ]
