# Generated by Django 4.2.7 on 2024-04-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triagem', '0478_triagem_nome_medico_respondeu_ao_chamado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento_especializado',
            name='situacao',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em atendimento', 'Em atendimento'), ('Liberado', 'Liberado')], default='Aguardando', max_length=30, null=True),
        ),
    ]
