# Generated by Django 4.1.4 on 2022-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ficha_de_atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(default='nome_social', max_length=30)),
                ('idade', models.CharField(default='00', max_length=2)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
