# Generated by Django 4.1.4 on 2022-12-11 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0002_alter_ficha_de_atendimento_nome_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero_sexual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField(default='Outros', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='CEP',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='CPF',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='RG',
            field=models.CharField(default='000.000.00-00', max_length=13),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='bairro',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='cidade',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='estado',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='nacionalidade',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='nome_mae',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='registro',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='responsavel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='rua',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='tel',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='data_nascimento',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='nome_social',
            field=models.CharField(default='nome_social', max_length=40),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Atendimento.genero_sexual'),
        ),
    ]
