# Generated by Django 4.1.4 on 2022-12-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0003_genero_sexual_ficha_de_atendimento_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='envio_triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio_triagem', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atendimento.ficha_de_atendimento')),
            ],
        ),
    ]
