# Generated by Django 4.1.4 on 2022-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0004_envio_triagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='horario_cadastro',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
