# Generated by Django 4.1.4 on 2022-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0005_ficha_de_atendimento_horario_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='horario_triagem',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio_triagem',
            name='data_envio_triagem',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
