# Generated by Django 4.1.4 on 2022-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0006_envio_triagem_horario_triagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='data_envio_triagem',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
