# Generated by Django 4.1.4 on 2022-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0007_alter_envio_triagem_data_envio_triagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='data_envio_triagem',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
