# Generated by Django 4.1.4 on 2023-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0012_alter_envio_triagem_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio_triagem',
            old_name='paciente',
            new_name='paciente_envio_triagem',
        ),
    ]
