# Generated by Django 4.1.4 on 2023-01-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0013_rename_paciente_envio_triagem_paciente_envio_triagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='paciente_envio_triagem',
            field=models.ForeignKey(default='Busque o paciente aqui', on_delete=django.db.models.deletion.PROTECT, to='Atendimento.ficha_de_atendimento'),
        ),
    ]
