# Generated by Django 4.1.4 on 2023-01-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0015_alter_envio_triagem_paciente_envio_triagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha_de_atendimento',
            options={'ordering': ['-data_cadastro']},
        ),
        migrations.RenameField(
            model_name='ficha_de_atendimento',
            old_name='registro',
            new_name='cartao_sus',
        ),
    ]
