# Generated by Django 4.1.4 on 2023-01-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0016_alter_ficha_de_atendimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['-data_envio_triagem']},
        ),
    ]
