# Generated by Django 4.1.4 on 2023-01-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0018_envio_triagem_data_triagem_concluida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='paciente_envio_triagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_ficha_atendimento', to='Atendimento.ficha_de_atendimento'),
        ),
    ]
