# Generated by Django 4.1.4 on 2023-01-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0019_alter_envio_triagem_paciente_envio_triagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={},
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q1',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q2',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q3',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q4',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q5',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q6',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q7',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q8',
            field=models.CharField(default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='envio_triagem',
            name='q9',
            field=models.CharField(default='', max_length=1, null=True),
        ),
    ]
