# Generated by Django 4.1.4 on 2023-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0020_alter_envio_triagem_options_envio_triagem_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='triagem_concluida',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
