# Generated by Django 4.1.4 on 2023-02-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0021_alter_envio_triagem_triagem_concluida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['horario_triagem', 'data_envio_triagem', 'paciente_envio_triagem__idade']},
        ),
    ]
