# Generated by Django 4.1.4 on 2023-02-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0022_alter_envio_triagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['horario_triagem', 'data_envio_triagem']},
        ),
    ]
