# Generated by Django 4.1.4 on 2023-02-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0023_alter_envio_triagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['horario_triagem', 'data_envio_triagem'], 'permissions': [('Acesso_permitido_envio_Tri', 'Acesso permitido para envio à Fila de Triagem')]},
        ),
        migrations.AlterModelOptions(
            name='ficha_de_atendimento',
            options={'ordering': ['-data_cadastro'], 'permissions': [('Acesso_permitido_atend', 'Acesso permitido para recepção  da UPA')]},
        ),
        migrations.AlterModelOptions(
            name='genero_sexual',
            options={'permissions': [('Acesso_permitido', 'Acesso permitido ao admin do sistema na UPA')]},
        ),
    ]
