# Generated by Django 4.1.4 on 2023-02-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0024_alter_envio_triagem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha_de_atendimento',
            options={'ordering': ['-data_cadastro']},
        ),
        migrations.AlterModelOptions(
            name='genero_sexual',
            options={},
        ),
    ]
