# Generated by Django 4.1.4 on 2023-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0025_alter_ficha_de_atendimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='idade',
            field=models.IntegerField(default='00', max_length=2),
        ),
    ]
