# Generated by Django 4.1.4 on 2023-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0026_alter_ficha_de_atendimento_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='cartao_sus',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
