# Generated by Django 4.1.4 on 2023-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0027_alter_ficha_de_atendimento_cartao_sus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='idade',
            field=models.IntegerField(default='00'),
        ),
    ]
