# Generated by Django 4.1.4 on 2023-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0028_alter_ficha_de_atendimento_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='nome_social',
            field=models.CharField(default='', max_length=40),
        ),
    ]
