# Generated by Django 4.2 on 2023-04-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0030_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Atendimento.bairro'),
        ),
    ]
