# Generated by Django 4.2 on 2023-04-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0031_rua_alter_ficha_de_atendimento_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_de_atendimento',
            name='rua',
        ),
    ]
