# Generated by Django 4.2 on 2023-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0033_ficha_de_atendimento_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='bairro_nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rua',
            name='rua_nome',
            field=models.CharField(max_length=100),
        ),
    ]
