# Generated by Django 4.2 on 2023-05-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0034_alter_bairro_bairro_nome_alter_rua_rua_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='alergias',
            field=models.CharField(choices=[('', ''), ('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='conteudo_alergia',
            field=models.TextField(default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)', max_length=300, null=True),
        ),
    ]
