# Generated by Django 4.2 on 2023-07-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0035_ficha_de_atendimento_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(max_length=100)),
                ('estado_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ficha_de_atendimento',
            name='estado',
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='cidade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.cidade'),
        ),
    ]
