# Generated by Django 4.2 on 2023-07-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0036_cidade_remove_ficha_de_atendimento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='estado',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='cidade',
            field=models.CharField(default='', max_length=30),
        ),
    ]
