# Generated by Django 4.2 on 2023-07-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0037_ficha_de_atendimento_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
