# Generated by Django 4.2 on 2023-07-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0038_delete_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etnia', models.CharField(default='Outros', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_atendimento_bairro', to='Atendimento.bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='sexo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.genero_sexual'),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='etnia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.etnia'),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_atendimento_pais', to='Atendimento.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='cidade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.cidade'),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='estado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.estado'),
        ),
    ]
