# Generated by Django 4.2 on 2023-07-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0039_cidade_estado_etnia_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.cidade'),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.estado'),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.genero_sexual'),
        ),
    ]
