# Generated by Django 4.2 on 2023-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0040_alter_ficha_de_atendimento_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='data_triagem_concluida',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
