# Generated by Django 4.2 on 2023-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0042_alter_envio_triagem_data_triagem_concluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='data_triagem_concluida',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
