# Generated by Django 4.2 on 2023-07-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0043_alter_envio_triagem_data_triagem_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='comorbidades',
            field=models.CharField(choices=[('', ''), ('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='conteudo_comorbidades',
            field=models.TextField(default='Não possui comobirdades (Para tornar editável essa área, é necessário informar que o paciente possui comobirdades)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='conteudo_alergia',
            field=models.TextField(default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)', max_length=500, null=True),
        ),
    ]
