# Generated by Django 4.2 on 2023-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0045_alter_ficha_de_atendimento_conteudo_alergia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='codigo_pacient',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
