# Generated by Django 4.2 on 2023-07-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0046_ficha_de_atendimento_codigo_pacient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.etnia'),
        ),
    ]
