# Generated by Django 4.2 on 2023-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0048_alter_ficha_de_atendimento_codigo_pacient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='alergias',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='comorbidades',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default=2, max_length=3),
        ),
    ]
