# Generated by Django 4.2.7 on 2023-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0050_alter_ficha_de_atendimento_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='comorbidades',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='0', max_length=3),
        ),
    ]
