# Generated by Django 4.2.7 on 2023-11-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0052_alter_ficha_de_atendimento_alergias'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenca_ativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiracao', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
