# Generated by Django 4.2.7 on 2023-11-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0053_licenca_ativa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='licenca_ativa',
        ),
    ]
