# Generated by Django 4.2.7 on 2023-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0054_delete_licenca_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiracao', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
