# Generated by Django 4.2.7 on 2023-11-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0055_licenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='envio_triagem',
            name='q9',
        ),
    ]
