# Generated by Django 4.2.7 on 2023-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0056_remove_envio_triagem_q1_remove_envio_triagem_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.BooleanField(default=False),
        ),
    ]
