# Generated by Django 4.2.7 on 2023-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0057_envio_triagem_retornou_em_menos_de_48_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='CPF',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='RG',
            field=models.CharField(default='', max_length=13),
        ),
    ]
