# Generated by Django 4.2.7 on 2023-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0058_alter_ficha_de_atendimento_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.BooleanField(null=True),
        ),
    ]
