# Generated by Django 4.2.7 on 2023-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0059_alter_envio_triagem_retornou_em_menos_de_48_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='0', max_length=3),
        ),
    ]
