# Generated by Django 4.2.7 on 2023-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0061_alter_envio_triagem_retornou_em_menos_de_48_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.BooleanField(default=True),
        ),
    ]
