# Generated by Django 4.2.7 on 2023-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0063_alter_envio_triagem_retornou_em_menos_de_48_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='nome_acompanhante',
            field=models.CharField(default='Ele mesmo', max_length=50, null=True),
        ),
    ]
