# Generated by Django 4.2.7 on 2023-12-24 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0064_envio_triagem_nome_acompanhante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='conteudo_alergia',
            field=ckeditor.fields.RichTextField(blank=True, default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)', null=True),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='conteudo_comorbidades',
            field=ckeditor.fields.RichTextField(blank=True, default='Não possui comobirdades (Para tornar editável essa área, é necessário informar que o paciente possui comobirdades)', null=True),
        ),
    ]
