# Generated by Django 4.2.7 on 2023-12-24 17:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0067_alter_ficha_de_atendimento_conteudo_alergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='conteudo_alergia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='conteudo_comorbidades',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
