# Generated by Django 4.2.7 on 2024-01-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0071_alter_ficha_de_atendimento_conteudo_alergia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['-horario_triagem', '-data_envio_triagem'], 'permissions': [('Acesso_permitido_envio_Tri', 'Acesso permitido para envio à Fila de Triagem')]},
        ),
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='0', max_length=1),
        ),
    ]
