# Generated by Django 4.2.7 on 2024-01-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0072_alter_envio_triagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='0', max_length=1, null=True),
        ),
    ]
