# Generated by Django 4.2.7 on 2024-01-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0074_alter_envio_triagem_retornou_em_menos_de_48_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='0', max_length=3),
        ),
    ]
