# Generated by Django 4.2.7 on 2024-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0080_envio_triagem_horas48'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='cod_triagem',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
