# Generated by Django 4.2.7 on 2024-02-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0081_envio_triagem_cod_triagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
        ),
    ]
