# Generated by Django 4.2.7 on 2024-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0083_alter_ficha_de_atendimento_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='retornou_em_menos_de_48_horas',
            field=models.BooleanField(default=False),
        ),
    ]
