# Generated by Django 4.2.7 on 2024-02-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0085_alter_ficha_de_atendimento_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='rua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Atendimento.rua'),
        ),
    ]
