# Generated by Django 4.2.7 on 2024-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0086_alter_ficha_de_atendimento_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='rua',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
