# Generated by Django 4.2.7 on 2024-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0089_alter_ficha_de_atendimento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_triagem',
            options={'ordering': ['-horario_triagem'], 'permissions': [('Acesso_permitido_envio_Tri', 'Acesso permitido para envio à Fila de Triagem')]},
        ),
    ]
