# Generated by Django 4.2.7 on 2024-03-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0092_ficha_de_atendimento_nome_recepcionista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_de_atendimento',
            name='prioridade',
        ),
    ]
