# Generated by Django 4.2.7 on 2024-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0093_remove_ficha_de_atendimento_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_triagem',
            name='prioridade',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='0', max_length=3),
        ),
    ]
