# Generated by Django 4.2.7 on 2024-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0094_envio_triagem_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='nome_completo',
            field=models.CharField(default='', max_length=50, verbose_name='Nome completo (Como está escrito no RG)'),
        ),
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='nome_social',
            field=models.CharField(default='', max_length=40, verbose_name='Nome Social (Como a pessoa que ser chamada no painel)'),
        ),
    ]
