# Generated by Django 4.2.7 on 2024-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0096_envio_triagem_nome_recepcionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_de_atendimento',
            name='nome_completo',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nome completo (Como está escrito no RG)'),
        ),
    ]
