# Generated by Django 4.2.7 on 2024-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0097_alter_ficha_de_atendimento_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_de_atendimento',
            name='data_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
