# Generated by Django 4.2.7 on 2024-04-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0098_ficha_de_atendimento_data_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_priority', to='Atendimento.ficha_de_atendimento')),
            ],
        ),
    ]
