# Generated by Django 4.2.7 on 2024-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0099_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro_Vera_Cruz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_nome', models.CharField(max_length=30)),
            ],
        ),
    ]
