from .triagem_enfermaria import *
from .triagem_enfermariaUpdate import *
from .triagem_enfermaria_Alergia_Update import *
from .triagem_classifica_Risco_update import *
from .EtiquetaView import *
from .triagem_concluida_Update import *
from .classifica_risco import *
from .criar_registros import *
from .atend_especializado import *
from .atend_especializado_ListView import *
from .atend_especializado_UpdateView import *
from .triagem_delete import *
from .nao_atendeu_chamado import *